### ISSUE TITLE
Use with hyprland-nix

### ISSUE THREAD

**Issue by hmajid2301** [catppuccin/nix#102]
Is there a way I can use this with hyprland-nix: https://github.com/hyprland-community/hyprland-nix. Which doesn't have the same options as the home-manager one.

Currently I get the following error:

```
    error: The option `wayland.windowManager.hyprland.settings' does not exist. Definition values:
       - In `<unknown-file>':
           {
             _type = "if";
             condition = false;
             content = {
               "\$base" = "rgb(1e1e2e)";
```

Because there is not `settings` field when using that flake. Is there a way to ignore the hyprland module in this flake? Probably more of a general question.  I haven't tried to enable catppuccin in hyprland btw.

Thanks

**Comment by getchoo** [comment]
> Is there a way I can use this with hyprland-nix

as we only provide support for official home-manager and nixos modules, we can't guarantee compatibility with those from a third party

in this situation though, there isn't much stopping our theming from working besides that option name (as far as i can tell). i think a good idea would be to open an issue upstream asking for the option to be renamed from `config` to `settings`, as that would help a lot with compatibility not just for us, but also previous users of the official home-manager module -- plus, `settings` is a bit more common of a name

> Is there a way to ignore the hyprland module in this flake? Probably more of a general question. I haven't tried to enable catppuccin in hyprland btw.

you should be able to disable the module the same way you [replace modules](https://nixos.org/manual/nixos/stable/#sec-replace-modules). taking from the [flakes readme example](https://github.com/catppuccin/nix?tab=readme-ov-file#usage), one of these options could work

```nix
{
  nixosConfigurations.host = pkgs.lib.nixosSystem {
    inherit system;
    modules = [
      catppuccin.nixosModules.catppuccin
      home-manager.nixosModules.home-manager
      {
        home-manager.users.user = {
          imports = [
            ./home.nix
            catppuccin.homeManagerModules.catppuccin
          ];
          
          # here's where we should be able to disable the module
          # sorry in advanced if this doesn't work :(
          disabledModules = [
            # using the relative file path
            "modules/home-manager/hyprland.nix"
            # or using the absolute path
            (catppuccin + "/modules/home-manager/hyprland.nix")
          ];
        };
      }
    ];
  };
}
```
