### ISSUE TITLE
Add global `enableAll` setting

### ISSUE THREAD

**Issue by becknik** [catppuccin/nix#115]
Hi,

I'd love to just add this flake to my inputs and use a global toggle to enable the theming on all programs I've installed.
This would've the benefit of not having to check on the progress of the program options now and then and to automatically get satisfied when there is a new program supported :)

What do you think?

PS: Thanks for your work!

**Comment by drupol** [comment]
Temporary solution: https://discourse.nixos.org/t/catppuccin-nix-the-soothing-pastel-theme-but-for-nix/42915/13?u=drupol
