### ISSUE TITLE
Port Request: Rofi

### ISSUE THREAD

**Issue by IQubic** [catppuccin/nix#118]
Rofi themes exist here: https://github.com/catppuccin/rofi
There are a ton of home-manager options that you can play with that should make this easier to do: https://nix-community.github.io/home-manager/options.xhtml#opt-programs.rofi.enable

Honestly, I'd be fine with just basic support if adding support for the Deathemonic version at the same time proves to be infeasible for some reason.

**Comment by IQubic** [comment]
Also, if possible, it would be good to add options to allow the user to set their own terminal and font.

**Comment by michaelBelsanti** [comment]
a rofi module was added in #108
