### ISSUE TITLE
Rofi support forces a default option for font that might not work with all users

### ISSUE THREAD

**Issue by IQubic** [catppuccin/nix#122]
The rofi themes provided by a recent commit seem to just use the default theme configs from https://github.com/catppuccin/rofi/tree/main/basic/.local/share/rofi/themes

The main issue with this is these 4 themes all have the same line 12: `font: "JetBrainsMono Nerd Font 14";`  This font isn't installed on my machine, and the options provided here don't give me any ways to change this. I'd prefer this to either install the required fonts for me, or give me a way to change the font myself.

**Comment by aloop** [comment]
Not sure if it is compatible with the way this module sets up the rofi theme, but in my configuration I use the theme and override the defaults like so:

```nix
{
  programs.rofi = {
    # ...
    theme = {
      "@theme" = theme.package + /rofi/catppuccin-${theme.variant}.rasi;

      "*" = {
        font = "monospace 14";
      };
    };
  };
}
```

Where `theme.package` is pkgs.catppuccin.

I'm sure the module could be adapted to support this.
