### ISSUE TITLE
Unreferenced Cursor File Is Stuck In Nix Store

### ISSUE THREAD

**Issue by IQubic** [catppuccin/nix#130]
So, I've noticed that the cursor files for the `Mocha-Blue` cursors are stuck in the store. I've run `sudo nix-collect-garbage -d` a number of times and the files remain in the store. I've searched through my entire config, and the only place I'm referencing is in my `home-manager` config, in this file: [theme.nix](https://gist.github.com/IQubic/562ecefaf272c729135426f4ee43d7c1)

What follows is a `nix-store --query` call that shows that the `Mocha-Blue` cursor files are still in the store.
```
[root@LATITUDE-NIXOS:/etc/nixos]# nix-store --query --referrers-closure /nix/store/qz1lqp3lqxwby21ggqh3dc2ck6bh2kyp-catppuccin-cursors-0.2.0-mochaBlue
/nix/store/qz1lqp3lqxwby21ggqh3dc2ck6bh2kyp-catppuccin-cursors-0.2.0-mochaBlue
/nix/store/80rc9jycx7hv3zb8fnp2yqfnvbsdqvwd-home-manager-path
/nix/store/yzgsmm16jg1spxsxwg3mrlhgs0xnidhi-hm_fontconfigconf.d10hmfonts.conf
/nix/store/b8gi7bg4vg9zggrgx9z2fq5g5b6nk8r1-home-manager-files
/nix/store/xyfl8n6xv3bj24q6phg483332la8sg3y-home-manager-generation
/nix/store/cbn3wc72d9xi6d1d15i8awwardxhk15n-unit-home-manager-avi.service
/nix/store/cwpr154zvl5h95lhhcbhxx1v84x3aa3j-system-units
/nix/store/yxidpw1lkrrf0hv5c4g28mjr4s5r52j2-user-environment
/nix/store/1i7i1nqyl1s0f4spgc26c0nah02mra9d-etc
/nix/store/5iwmncfmwfyplk6mqpbrifbcrlhqg0vh-nixos-system-LATITUDE-NIXOS-24.05.20240416.5672bc9
```

**Comment by getchoo** [comment]
> I've run sudo nix-collect-garbage -d a number of times

have you run it as a regular user? this may be a leftover from a previous home-manager generation in `~/.local/state/nix/profiles`

**Comment by IQubic** [comment]
I have actually collected garbage as a regular user too.
