### ISSUE TITLE
GTK theme error: 'border-spacing` is not a valid property name

### ISSUE THREAD

**Issue by IQubic** [catppuccin/nix#141]
So, I was looking at `journalctl` output in order to resolve a completely different problem, and noticed a log message saying `Theme parsing error: gtk.css:7763:16: 'border-spacing' is not a valid property name`. Turns out that, if I run any GTK app from the terminal, I get the same error message printed to the terminal.

After doing some testing, I have found that this issue only occurs when the Home-Manager module option `gtk.catppuccin.enable` is set to true.

**Comment by getchoo** [comment]
this seems to be an issue with the [port itself](https://github.com/catppuccin/gtk). i would recommend opening an issue there instead

if i'm wrong feel free to re-open, though :)
