### ISSUE TITLE
Are global color overrides possible?

### ISSUE THREAD

**Issue by mrjones2014** [catppuccin/nix#148]
It looks like this is just downloading the respective config files from the other catpuccin repos, but I'm wondering if it would be possible to do global color overrides?

For example if I wanted a darker background color, it would be nice to be able to do that globally like 

```nix
catppuccin = {
  enable = true;
  flavor = "mocha";
  color_overrides = {
    mocha = {
      base = "#[some other color code]";
    };
  };
};
```

**Comment by getchoo** [comment]
no; if you want something like that, [nix-colors](https://github.com/misterio77/nix-colors) maybe be a better option. these modules are meant to only support themes directly from our other ports
