### ISSUE TITLE
Support NixOS & home-manager's stable branches

### ISSUE THREAD

**Issue by getchoo** [catppuccin/nix#155]
i.e., `23.11`, `24.05`. for now we target and test against `nixos-unstable` and the `master` branch of home-manager

recommendations on how to approach this are welcome :)

**Comment by vdbe** [comment]
Maybe something like 

```nix
  mkVersionedOpt = minimumVersion: opt:
    if (lib.strings.versionAtLeast "23.05" minimumVersion)
    then opt
    else lib.options.mkSinkUndeclaredOptions {};
```
```nix
  options.programs.tofi = ctp.mkVersionedOpt "24.05" {
    catppuccin = ctp.mkCatppuccinOpt "tofi";
  };
```

Tested it with https://github.com/Misterio77/nix-starter-configs and it builds.

Don't know the best way to get the home manager version, maybe `lib.version` but that is from nixpkgs not home manager.

https://github.com/vdbe/catppuccin-nix/tree/feat/versioned-options

**Comment by Lichthagel** [comment]
> Don't know the best way to get the home manager version (hardcoded to "23.05" here), maybe `lib.version` but that is from nixpkgs not home manager.

There is `config.home.version.release`: https://github.com/nix-community/home-manager/blob/f8e6694edabe4aaa7a85aac47b43ea5d978b116d/modules/misc/version.nix#L53-L60

**Comment by vdbe** [comment]
Forgot that internal doesn't show on search.

`config.home.version.release or config.system.nixos.version` would work covers home manager and nixos.

**Comment by vdbe** [comment]
Was trying to add a warning, but don't think it is possible:
- `else lib.trivial.warn "warning" (lib.options.mkSinkUndeclaredOptions {});` and `else lib.options.mkSinkUndeclaredOptions (lib.trivial.warn "warning" {});` warn always.
- `else lib.options.mkSinkUndeclaredOptions {default = lib.trivial.warn "warning" opt;};` never warns.

**Comment by becknik** [comment]
I'm using nixos & home-manager 23.11 and am currently stuck in a

```
       error: attribute 'enable' missing

       at /nix/store/flqfgj6fnp3cqfy19041lw4j1lhds76n-home-manager/tofi.nix:9:26:

            8|   cfg = config.programs.tofi.catppuccin;
            9|   enable = cfg.enable && config.programs.tofi.enable;
             |                          ^
           10| in
```

I don't have any experience in the maintenance in multi-version targeting projects, but I'd use git branches for the version separations. This would avoid cluttering the source code and enable easy backporting if a component of home-manager/ nixos gets backported too (if there is the wish to do this, of course).
E.g. the [nixvim](https://github.com/nix-community/nixvim) project handles it like this.
