### ISSUE TITLE
GTK themes are not applied correctly

### ISSUE THREAD

**Issue by nikololiahim** [catppuccin/nix#157]
I have the following home-manager GTK config:

```nix
  catppuccin.flavour = "mocha";

  ...

  gtk = {
    enable = true;
    catppuccin = {
      enable = true;
      size = "compact";
      accent = "pink";
      tweaks = [ "rimless" ];
      cursor = {
        enable = true;
        accent = "dark";
      };
    };
  };

```

When I switch to this config using `home-manager switch --flake`, all the GTK apps have the white background. I have tried different revisions of `catppuccin/nix` flake and figured out that `1fbdfdacf96c14449aea52edba895e5ab419dd13` seems to be the culprit.

Example GTK app before `1fbdfdac`:
![image](https://github.com/catppuccin/nix/assets/45356788/c91947ca-4a40-4616-a424-826987ddc140)

After:
![image](https://github.com/catppuccin/nix/assets/45356788/a3d8f769-5cf4-4f84-ba29-fc80d5b82f79)

**Comment by isabelroses** [comment]
The change to "Dark" -> "dark" and etc was made in regards to the upstream catppuccin/gtk. But nixos/nixpkgs still has not received these changes the maintainer has been contacted and hopefully this will be fixed soon.

**Comment by nikololiahim** [comment]
I see, thank you! Then a temporary workaround would be to just pin the flake's git
rev and switch back to master when the GTK changes hit the unstable nixpkgs branch.

**Comment by isabelroses** [comment]
The situation is a lot more complex then we first though. catppuccin/gtk uses a pinned commit submodule but nixos/nixpkgs uses a colloid release to build the catppuccin theme so even if we update catppuccin/gtk on nixpkgs the fix won't work so we are just going to roll back the change.

**Comment by getchoo** [comment]
based on the comments in #147 and #159 being merged, this should be fixed. feel free to re-open if there are any more issues :)
