### ISSUE TITLE
Expose `lib.ctp` to `config.lib.ctp`

### ISSUE THREAD

**Issue by Weathercold** [catppuccin/nix#167]
I'm working on exposing lib to config instead of extending nixpkgs' lib so that users can have access to some useful functions like `mkUpper`

@getchoo are you open to this?

**Comment by getchoo** [comment]
most of my thoughts can be summed up here https://github.com/catppuccin/nix/issues/96#issuecomment-2041403103 and in [a PR](https://github.com/catppuccin/nix/pull/97) that implemented this already

as a tl;dr (and more specific to our library): exposing our lib to `config` wouldn't make much sense imo, as it's not an actual option. a proper way to do this would be a pure flake output or an importable version -- the latter of which [we do have](https://github.com/catppuccin/nix/blob/e5322f7b4001aa8aab38ca5a0f42cafc590f42b6/modules/nixos/default.nix#L3) and *can* be used by others, but i understand it's not a nice way to do it

i don't think we should explicitly expose our lib in general though, as that would give us a much broader public api (and thus more pressure to keep it stable), and honestly? i'm not sure how useful most of our functions are. there are a few like you mentioned with `mkUpper`, but in general this isn't the case. i would also say it's a bit out of scope for this project to provide general utilities

**Comment by Weathercold** [comment]
Good point
