### ISSUE TITLE
Document modules that need Allow From Derivation

### ISSUE THREAD

**Issue by vdbe** [catppuccin/nix#172]
An extra readme segment that specifies which modules require Allow From Derivation
or/and an option to exclude those modules from the global enable option.

**Comment by vdbe** [comment]
Willing to implement it myself.

**Comment by getchoo** [comment]
documenting what modules contain it would be nice. feel free to PR it to our FAQ

regarding excluding them from the global enable option: i can see why this might be a requested feature, but i feel would overcomplicate how we actually implement `catppuccin.enable` for what's a pretty niche feature. giving a neat list of modules should be good enough for most i'd imagine

**Comment by vdbe** [comment]
For the option my idea was to have 1 place (2 nixos and home manager) where you use `mkOverride` with priority over `MkDefaultOption`.

This way you don't need to touch `mkCatppuccinOpt` and can possibly generate the description for documentation instead of a Readme/FAQ segment.

Don't know yet how you would test it so that it is not a best effort option.

Would this implementation be overcomplicated?

**Comment by mightyiam** [comment]
From my experience, `nix flake show` can fail due to these. Perhaps that could impact how niche we perceive this issue to be.

**Comment by alejandro-angulo** [comment]
I just wanted to chime in and mention that the kitty IFD shouldn't be required in upstream anymore. We'll have to switch to setting `themeFile` instead of `theme` now though.

https://github.com/nix-community/home-manager/pull/5750

**Comment by vdbe** [comment]
Someone is already working on this, see #337.

**Comment by getchoo** [comment]
This was meant to be closed by https://github.com/catppuccin/nix/pull/246. Thanks for all the work done here!
