### ISSUE TITLE
Feature request: gtk cursor: be able to set the size

### ISSUE THREAD

**Issue by bbigras** [catppuccin/nix#176]
On my laptop with sway, I usually need to increase the size of the cursor.

I use this right now:
```nix
{
  home.pointerCursor = {
    package = pkgs.bibata-cursors;
    name = "Bibata-Modern-Ice";
    size = 22;
  };
}
```

My screen resolution is: 3200x1800

Tbh, I don't know if setting the cursor size is the right way to fix it or not.

**Comment by getchoo** [comment]
you can set the gtk cursor size with the home manager option [`gtk.cursorTheme.size`](https://nix-community.github.io/home-manager/options.xhtml#opt-gtk.cursorTheme.size), along with the size variant of theme itself with our [`gtk.catppuccin.size`](https://github.com/catppuccin/nix/blob/9999d33b51988644c9cdddc58f317689b3974fbe/docs/home-manager-options.md#gtkcatppuccinsize) option

feel free to re-open if you still have issues :)

**Comment by bbigras** [comment]
I don't seem to have a bigger cursor when I use:

```nix
{
  gtk.cursorTheme.size = 22;

  gtk = {
    enable = true;
    catppuccin = {
      enable = true;
      cursor.enable = true;
    };
  };
}
````
