### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by mightyiam** [catppuccin/nix#177]
Hey, thank you for this!

I was wondering how I could get notified of new modules (however infrequently that may occur).

So I was thinking releases. Just a thought.

**Comment by getchoo** [comment]
see https://github.com/catppuccin/nix/issues/125 for some previous discussion on this

to clear things up: i am sticking with semantic versioning as that is what's widely understood by both users and flake registries such as flakehub and flakestry. everything listed under the [current milestone](https://github.com/catppuccin/nix/milestone/1) is what i consider a blocker for this initial release, which should be soon :)

the changelogs of these releases will be on the github release page and mirrored on the website being introduced in #170
