### ISSUE TITLE
The option `qt.style' does not support nested options

### ISSUE THREAD

**Issue by Krymancer** [catppuccin/nix#202]
I'm trying to use this but I'm getting this error:

```
error: The option `qt.style' in module `/nix/store/b2xy0gk6sd3fc8zamarfzach5f3wpkvi-source/nixos/modules/config/qt.nix' would be a parent of the following options, but its type `null or one of "adwaita", "adwaita-dark", "adwaita-highcontrast", "adwaita-highcontrastinverse", "bb10bright", "bb10dark", "breeze", "cde", "cleanlooks", "gtk2", "kvantum", "motif", "plastique"' does not support nested options.
        - option(s) with prefix `qt.style.catppuccin' in module `/nix/store/wqmfkfd7kcsa935ky2vf94x5cjz3r2vq-source/modules/home-manager/kvantum.nix'
```

**Comment by Krymancer** [comment]
> I am getting this error, is there a fix ?

I got this because I wasn't importing my home manager.

In my current configuration I setup a user in users.nix and import the nix file from users.nix, not from flake directly

**Comment by cootshk** [comment]
I'm having the same problem - @jerbaroo did you get a fix?

importing home manager doesnt help

also see [this thread](https://discord.com/channels/907385605422448742/1255298078806900786) in the catppuccin discord

**Comment by eliandoran** [comment]
For me the issue was that I had imported `catppuccin.homeManagerModules.catppuccin` directly in `home-manager.nixosModules.home-manager` instead of putting it inside `home-manager.users.<name>`. 

```diff
nixpkgs.lib.nixosSystem {
    catppuccin.nixosModules.catppuccin

    home-manager.nixosModules.home-manager {
-        imports = [
-            catppuccin.homeManagerModules.catppuccin
-        ];
+        home-manager.users.foo = {
+            imports = [
+                catppuccin.homeManagerModules.catppuccin
+            ];
+        };
    }
}
```
