### ISSUE TITLE
Global `catppuccin.enable` option may produce errors 

### ISSUE THREAD

**Issue by danielgafni** [catppuccin/nix#205]
I just encountered an issue when enabling the global `catppuccin.enable` setting. 

For whatever reason I had `swaylock` installed & configured via `packages` and `xdg.configFile."swaylock"` instead of `programs.swaylock.enable`. 

This caused a recursion error when setting `catppuccin.enable = true;`. It took me a while to understand the issue. 

It seems like this could be handled better. `catppuccin-nix` probably should have no effect on a package which is not installed via `programs.<x>.enable`.

**Comment by isabelroses** [comment]
For some modules it makes sense to do what you say. But for others it makes just as much sense to do something like https://github.com/catppuccin/nix/blob/2c7661c9fa26a920b8088300ef87d14179c71a27/modules/home-manager/bottom.nix#L12

Which is particularly important for a module like [hyprland](https://github.com/catppuccin/nix/blob/main/modules/home-manager/hyprland.nix), since it loads var for users to utilise.

Its also also perticularly easy to enforce this standard.

**Comment by danielgafni** [comment]
Oh right, makes sense. 

In any case, recursion errors should not happen :)

**Comment by isabelroses** [comment]
> In any case, recursion errors should not happen :)

This is 100% true.

**Comment by getchoo** [comment]
> This caused a recursion error when setting catppuccin.enable = true;. It took me a while to understand the issue.

would you be able to provide a log? this seems like a pretty big issue, but i'm not at all sure where it could be coming from

> configured via packages and xdg.configFile."swaylock" instead of programs.swaylock.enable

my only guess is that this may have to with both you and the module setting the `configFile` option, but that should never apply unless our module is enabled (with global `catppuccin.enable` it will be) *and* the home-manager swaylock module ([source](https://github.com/catppuccin/nix/blob/2c7661c9fa26a920b8088300ef87d14179c71a27/modules/home-manager/swaylock.nix#L5))

**Comment by danielgafni** [comment]
[Here](https://github.com/danielgafni/nixos/actions/runs/9414842862/job/25934574649) is a recent error message from my GitHub Actions

It started happening after [this](https://github.com/danielgafni/nixos/pull/51/commits/3f04e515a48d29d91364765c595bfed59e0209cb) commit where I simply removed `swaylock`.

**Comment by isabelroses** [comment]
I've heard Nobbz say `config = mkIf cond` is a dangerous pattern. Unsure if this is related but a number of other programs don't use this pattern. Might be worth changing it for the sake of testing.

**Comment by getchoo** [comment]
hi! sorry for the wait, been a bit busy with some things IRL

i've done a bit of digging into this and i haven't quite been able to figure out what exactly caused this in your configuration, or where it could possibly pop up in others. given the following minimum viable configuration of our modules

```
nix-repl> (pkgs.nixos {
            imports = [ ./modules/nixos inputs.home-manager.nixosModules.home-manager ];
            users.users.test = { isNormalUser = true; home = "/home/test"; };
            home-manager.users.test = { imports = [ ./modules/home-manager ]; catppuccin.enable = true; home.stateVersion = "24.11"; };
            system.stateVersion = "24.11";
          }).config.system.build.vm
```

this seems to work as expected. when i have the time i'll try to debug this a bit more, but given that this doesn't seem to be easy to trigger by just using the global `catppuccin.enable` and no one else reporting this, i'm going to take it off the 1.0.0 milestone for now as it seems to be an isolated issue

**Comment by y-usuzumi** [comment]
Hi! I have run into the same issue today. I'm not a Nix expert so I'm not sure how I can help. But I also found "swaylock" in the stacktrace which I have never used. I'm running Plasma 6 only.

https://pastebin.com/8KDKJjrL

**Comment by danielgafni** [comment]
My config is different now, and since you've checked the fix with the old commit, I believe it should be fine. Thanks for the fix!
