### ISSUE TITLE
Namespace our module options

### ISSUE THREAD

**Issue by getchoo** [catppuccin/nix#222]
Currently we use existing option namespaces for our own (i.e., our options for `programs.bat` are under `programs.bat.catppuccin`), which can introduce some issues in options that use submodule as their type. To avoid this, it'd probably be best to use the already existing `catppuccin` namespace for all of our options (an example of this would be `catppuccin.programs.bat`)

This would break basically every option we have currently, but would hopefully avoid problems in the future as things like the freeform type become more widely adopted

Thanks to @Weathercold for suggesting this

**Comment by isabelroses** [comment]
This doesn't seem like a bad Idea when you take into accound we are creating our own `programs.glamour` which might be taken by another program later if home-manager does something.

See: https://github.com/catppuccin/nix/blob/85558d1638a65ed1cc7fb8bd7cfc1a5474b21fdb/modules/home-manager/glamour.nix

**Comment by Airradda** [comment]
As a user, this will make it a lot easier to quickly enable all the module options with a copy paste of the whole `catppuccin.*`, as well as easily tell which I have enabled, which will be especially important as more of them get continually added. The only issue/inconvenience I can imagine, for me at least, is in the symbol picker of a [Nil](https://github.com/oxalica/nil)+[Helix](https://github.com/helix-editor/helix/) these module options will likely be sorted before the Home-Manager ones (`catppuccin.programs.bat` then `programs.bat`).

**Comment by isabelroses** [comment]
> symbol picker of a [Nil](https://github.com/oxalica/nil)

This is a bit of a problem but nixd on the other hand should be able to handle this. Although nixd is not preferable if your using lix.

**Comment by getchoo** [comment]
Finished in https://github.com/catppuccin/nix/pull/371
