### ISSUE TITLE
Grub's boot-menu cuts off NixOS generation text

### ISSUE THREAD

**Issue by egirlcatnip** [catppuccin/nix#223]
Catppuccin grub's boot-menu box width is 480 pixels - 25% of 1920px screen. 
This is too narrow to show the full NixOS boot generation text

Currently looks like this:
![image](https://github.com/catppuccin/nix/assets/26607304/4c49900f-543a-4e28-858c-fc63fd954a63)

I propose an increase to 35% or 40%, which should be enough, either as a percentage or a value of 672 or 768 pixels

**Comment by getchoo** [comment]
as this is an upstream port issue, i'm going to close this. feel free to update us when it's resolved, though :)

**Comment by isabelincorp** [comment]
Resolved as complete with https://github.com/catppuccin/grub/issues/21#issuecomment-2558343902
