### ISSUE TITLE
Feature request: custom palettes

### ISSUE THREAD

**Issue by jerbaroo** [catppuccin/nix#228]
What this packages achieves is quite amazing: I use this package not particularly because I want a Catppuccin themed system, but because it is the best experience I found to easily achieve theming across applications with NixOS and home-manager.

I wonder if you have considered adding support for custom palettes, beyond the four defined by Catppuccin theme. For example, instead of defining a flavor as "mocha" one might define a flavor by giving a color palette directly as 12 greyscale colors (base, crust, etc.) and 14 rainbow colors (red, blue, etc..).

**Comment by isabelroses** [comment]
You can override the sources if that's what you're looking for, https://nix.catppuccin.com/options/home-manager-options.html#catppuccinsources. This is how anything that is generated with the catppuccin palette or sources. Other then that this request is out of scope.
