### ISSUE TITLE
Will all the GTK related options be removed soon?

### ISSUE THREAD

**Issue by stelcodes** [catppuccin/nix#231]
Now that the [official GTK theme is archived indefinitely](https://github.com/catppuccin/gtk/commit/23b52b5b9cde1e11c07315e79a55804d2ac77e3a), will the `gtk.catppuccin.*` options go away? I'm considering adding this project into my Nix config but my main use case is GTK theming so I'd like to know if the options will suddenly disappear.

**Comment by jilinoleg** [comment]
It seems as it will be, since this warning got added if you try to use it:
```console 
warning: username profile: `gtk.catppuccin` is deprecated and will be removed in a future release.

The upstream port has been archived and support will no longer be provided.
Please see https://github.com/catppuccin/gtk/issues/262
```

**Comment by stelcodes** [comment]
That's what I feared... It just seems so silly to abandon one of the best GTK themes like this. Oh well. I'll just keep using the older versions because they work perfectly for me on Sway.
