### ISSUE TITLE
No themes are applying

### ISSUE THREAD

**Issue by Different-Name** [catppuccin/nix#232]
Catppuccin themes are not applying in any applications

I have enabled catppuccin in both my home manager and nixos configurations using
`catppuccin.enable = true;`
I have set my accent and flavor with
`catppuccin.accent = "red"`
`flavor = "mocha"`

I am using the provided flake and have included the home manager module it provides

**Comment by uncenter** [comment]
Have you enabled it for each program? See https://github.com/uncenter/flake/blob/4f250e7f760486085a3415c9dd3e0d075e0adf54/home/programs/bat.nix#L4.

**Comment by Different-Name** [comment]
I have manually enabled fish, kitty, waybar, mako and hyprland

Nothing has applied still unfortunately

**Comment by uncenter** [comment]
Do you have dotfiles we can look at? Seems like a configuration issue on your end still.

**Comment by Different-Name** [comment]
Yep, it's [here](https://github.com/Different-Name/nixos-config/tree/master)

It is most likely an issue on my end - I am quite new to NixOS

**Comment by isabelroses** [comment]
Your current installing kitty separately. you should do
```nix
{
  programs.kitty = {
    enable = true;
    catppuccin.enable = true;
  };
}
```

**Comment by Different-Name** [comment]
Ah, that fixed it 🥲

I'm going to assume waybar needs some kind of configuration to work with the module - I'll look into that

**Comment by isabelroses** [comment]
> Ah, that fixed it 🥲
> 
> I'm going to assume waybar needs some kind of configuration to work with the module - I'll look into that

Waybar should just be the same
```nix
{
  programs.waybar = {
    enable = true;
    catppuccin.enable = true;
  };
}
```

**Comment by Tebro** [comment]
I have this issue as well, I tried to understand what is wrong based on this discussion and the linked repo but the setup is wildly different from my own. 

My flake: https://github.com/Tebro/nix-flake
