### ISSUE TITLE
Overriding catppuccin flavor for individual hm modules

### ISSUE THREAD

**Issue by erdfern** [catppuccin/nix#237]
A bit of a nix noob question: I was wondering how I'd override the flavor for a specific home manager module. For example, I've set my global catppuccin config like so:
```nix
  catppuccin.enable = true;
  catppuccin.flavor = "macchiato";
  catppuccin.accent = "maroon";
```

But I'd like zathura to use "latte" instead of "macchiato". Can I override the `catppuccin.flavor` for "programs.zathura" specifically?

Sorry if this is very basic, I'm not very experienced with Nix yet ;-;

**Comment by vdbe** [comment]
That is possible see: https://nix.catppuccin.com/options/home-manager-options.html?highlight=zathura#programszathuracatppuccinflavor

**Comment by erdfern** [comment]
Oh pardon, I thought I tried that but I misspelled catppuccin as catpuccin.flavor :sob: ty though

**Comment by vdbe** [comment]
No problem, misspelling cappuccin is a tradition.
