### ISSUE TITLE
Maintain our own derivations of ports where necessary

### ISSUE THREAD

**Issue by getchoo** [catppuccin/nix#240]
this should help resolve issues where changes in modules are made to address package updates that have reached unstable, but not stable yet. it will also prevent release blockers due to nixpkgs PRs such as those mentioned in https://github.com/catppuccin/nix/pull/65#issuecomment-2184295348

**Comment by isabelroses** [comment]
Would we be using nixpkgs as a flake input or via nvfetcher?

**Comment by getchoo** [comment]
I think we'll just use the nixpkgs from the system in the module
