### ISSUE TITLE
Importing Home Manager creates a conflicts with Hyprland (even disabled)

### ISSUE THREAD

**Issue by DeltaCircuit** [catppuccin/nix#268]
> flake.lock
```json
{
  "locked": {
    "lastModified": 1719758387,
    "narHash": "sha256-bMaI1jJNzIZar4TP/hhoPQROqqcbD6zT6O+sqIJdp8c=",
    "owner": "catppuccin",
    "repo": "nix",
    "rev": "9eb0610d48dd0e1fecf772bbdacf9050d7b82d7c",
    "type": "github"
  },
  "original": {
    "owner": "catppuccin",
    "repo": "nix",
    "type": "github"
  }
}
```

And imported the home manager module as 
```
catppuccin.homeManagerModules.catppuccin
```

I'm using Sway and not enabled Hyprland and yet, when I try to import the HM module, it throws an error like below.

![image](https://github.com/catppuccin/nix/assets/2258588/0965203f-400f-4f95-8199-82c90b055e00)

What am I missing?

**Comment by getchoo** [comment]
i would need more context here. i'm guessing that this module was either not imported under your home-manager user, or you're using a very outdated version of home-manager that doesn't include support for hyprland

**Comment by DeltaCircuit** [comment]
@getchoo I'm on the latest home-manager. For reference, [here's the flake input](https://github.com/DeltaCircuit/nixos.config/blob/dd30b9a2e3569f364d31c03451312dc570165d2e/flake.nix#L66) and [I'm importing HM module here](https://github.com/DeltaCircuit/nixos.config/blob/dd30b9a2e3569f364d31c03451312dc570165d2e/home/default.nix#L12). This definitions is added to the home-manager user [here](https://github.com/DeltaCircuit/nixos.config/blob/dd30b9a2e3569f364d31c03451312dc570165d2e/hosts/precision/users/giri/home.nix#L7)

**Comment by getchoo** [comment]
@DeltaCircuit i'm fairly sure this is a known conflict with hyprland-nix - which you use [here](https://github.com/DeltaCircuit/nixos.config/blob/dd30b9a2e3569f364d31c03451312dc570165d2e/home/wms/hyprland/default.nix#L25). this was previously discussed in https://github.com/catppuccin/nix/issues/102, along with a workaround at the end of [this comment](https://github.com/catppuccin/nix/issues/102#issuecomment-2046570327)

if it doesn't work out for you or i'm wrong here, feel free to re-open :)

**Comment by DeltaCircuit** [comment]
@getchoo thanks for the response! I didn't see the previous issue, and yes both are same. 

But even after commenting out the module, it's still persists. Any clue what's going on here?

The current import / disable looks like this

```nix
imports = [
  inputs.catppuccin.homeManagerModules.catppuccin
];

disabledModules = [
  "${inputs.catppuccin}/modules/home-manager/hyprland.nix" # This didn't work
  "${inputs.catppuccin.outPath}/modules/home-manager/hyprland.nix" # This didn't work either
];
```

I think I'm missing something very silly, could you help me out here? I'm still taking baby steps on Nix / NixOS.
