### ISSUE TITLE
IFD at all

### ISSUE THREAD

**Issue by mightyiam** [catppuccin/nix#289]
For example:

https://github.com/catppuccin/nix/blob/d75d5803852fb0833767dc969a4581ac13204e22/modules/lib/default.nix#L81-L89

Calling `readFile` on a derivation (created using `runCommand`) is [IFD](https://nix.dev/manual/nix/2.22/language/import-from-derivation).

I suppose one thing that would have avoided this is to be able to parse INI in pure Nix.

But even if we had that, I'm not sure — could anyone illumine me please — would it be IFD anyway?

If that's the case, would git submodules possibly help avoid IFD?

**Comment by getchoo** [comment]
I don't think the usage of IFD in these modules *at all* is much of an issue. IFD -- while a bit of a sledgehammer solution and something that should be avoided -- does exist in Nix for a reason, and I feel we use it for it's intended purpose here

> would git submodules possibly help avoid IFD?

And while yes this (or other ways of vendoring local files) would help in some of our cases, I wouldn't say it's worth the maintenance cost. Our current system of using fetchers works very well, and also opens the door for end users to easily override these sources; In contrast, submodules aren't the most friendly way to update external sources, or to deal with when fetching this repository (i.e., as a flake input)

I think a better solution would be to work with home-manager and nixpkgs upstream to improve the IFD situation in modules directly, while letting users know where it occurs here so they can avoid it if they want to (like in https://github.com/catppuccin/nix/pull/246, which I promise to finally merge soon :p). A tracking issue could help out here if you wish to pursue this further

In any case, as this is not exactly a bug I'm closing as WONTFIX

**Comment by getchoo** [comment]
> Well, [it seems that now "everything" depends on IFD](https://github.com/catppuccin/nix/discussions/463#discussioncomment-12038880).

I think there's a misunderstanding here. Nowhere does Isabel say that "everything" requires IFD. She actually says

>  Some ports will need to use IFD [...] But some other ports [...] can avoid using IFD

You were correct in your original discussion post that the README is out of date in this area. We're using https://github.com/catppuccin/nix/issues/392 to track it now, as that's a bit easier to edit and for people to participate in; the README section will most likely be replaced with a link to it

Based on that issue and a quick [search](https://github.com/search?q=repo%3Acatppuccin%2Fnix+path%3Amodules+%22importTOML%22+OR+%22importJSON%22+OR+%22importINI%22+OR+%22importYaml%22+OR+%22readFile%22&type=code), I believe there are at most 12-13 modules that require IFD, out of our ~60 modules overall. So while those cases do line up with the programs you use, I hope you understand this is far from "everything"

>  I think IFD is more commonly for cases where there's a build process to obtain whatever is later used in evaluation

The build process in this case is fetching the remote source, patching them if required, and installing the theme files from it. This is done for every port source

Some functions like `fromYAML` and `fromINI` use external commands to transpile files to formats Nix understands. These derivations are then imported to use in module options

> Practically though, what would be the harm in using builtins.fetchTarball, instead?

The biggest issue nowadays would be in we can't, really. Ports are now individually packaged by only installing specific files from them to store paths, which helps save on storage, clean up implementation in modules, and for people (us maintainers included) to modify them. Even if we used builtin fetchers for the sources, the source would still be used to build a derivation

But say we go back to using entire repos with the built in fetchers. We still have issues:

As I've said [before](https://github.com/catppuccin/nix/pull/377), similar to IFD, builtin fetchers block evaluation -- as well as have issues with other things like substituters, but performance is most relevant in our case. This is why like IFD, they're [not allowed in Nixpkgs](https://nixos.org/manual/nixpkgs/stable/#chap-pkgs-fetchers)

For the dozen or so of our modules that are already performing IFD, there would be no difference performance-wise; you would *only* be avoiding the IFD flag going off from Nix. In contrast, all other modules *not* already performing IFD would now block evaluation and severely hinder performance. So, considering how few modules require IFD and the likelihood of them seeing alternatives introduced to avoid it, switching to builtin fetchers broadly isn't a great solution for us when it would negatively impact a vast majority of users

---

The (not very) solution I would recommend when using modules that currently require IFD is to make sure it's allowed by Nix. This can be done by setting [`allow-import-from-derivation`](https://nix.dev/manual/nix/2.24/command-ref/conf-file.html#conf-allow-import-from-derivation) to `true` in `nix.conf`/`nix.settings`, or by passing `--allow-import-from-derivation` to commands like `nix flake show`
