### ISSUE TITLE
Inconsistent scale in applications

### ISSUE THREAD

**Issue by wizardlink** [catppuccin/nix#292]
Hello there! Recently moved to this amazing port, however I've had the unfortunate problem of apps having a weird scaling in my system, specifically:
![image](https://github.com/user-attachments/assets/0497635f-44cc-493e-8fb1-6c60283c2ded)

As seen in this case, the application's font is **really** small, alongside it's icons and everything else, I am not sure what part of it is causing it and what could I change to fix the problem.

For reference, this is my terminal beside qBittorrent:
![image](https://github.com/user-attachments/assets/1a3ef5d4-1c55-4b1c-b921-54fa42cbe8bd)

I appreciate in advance!

**Comment by getchoo** [comment]
I would imagine this is either an issue with your system's Qt configuration or the upstream port -- I recommend reporting this to https://github.com/catppuccin/Kvantum first

Feel free to re-open if you find we're at fault though!
