### ISSUE TITLE
Wezterm support

### ISSUE THREAD

**Issue by SymphonySimper** [catppuccin/nix#305]
Hi there, it would be great if we can integrate wezterm. 
Wezterm port: https://github.com/catppuccin/wezterm

**Comment by pinkcreeper100** [comment]
as far as i know, the way wezterm is configured, it is impossible to do so

however catppuccin is integrated into wezterm's theme database 

i have it set like this: https://git.gay/oli/nix-config/src/branch/main/modules/home/desktop/wezterm/default.nix#L27

**Comment by pinkcreeper100** [comment]
although actually, could add it to  `programs.wezterm.colorSchemes`
but you'd still have to manually set the theme

**Comment by SymphonySimper** [comment]
> as far as i know, the way wezterm is configured, it is impossible to do so
> 
> however catppuccin is integrated into wezterm's theme database
> 
> i have it set like this: https://git.gay/oli/nix-config/src/branch/main/modules/home/desktop/wezterm/default.nix#L27

Yep, I've done the same using a Nix variable. So I was just wondering if it's possible to do this via a Nix module. Thank you for your response!
