### ISSUE TITLE
Path of k9s skin is broken on Darwin when XDG_CONFIG_HOME is unset

### ISSUE THREAD

**Issue by m-wynn** [catppuccin/nix#310]
On Darwin, If `XDG_CONFIG_HOME` is set, k9s will use that path for its files (e.g. `~/.config/k9s`.  If it is unset, k9s will use `~/Library/Application\ Support/k9s`.

Right now, catppuccin/nix will always use the [xdg path](https://github.com/catppuccin/nix/blob/main/modules/home-manager/k9s.nix#L19).

[Home-manager](https://github.com/nix-community/home-manager/blob/086f619dd991a4d355c07837448244029fc2d9ab/modules/programs/k9s.nix#L172-L180) gets around this with the following:

```nix
    skinFiles = mapAttrs' (name: value:
      nameValuePair (if !(isDarwin && !config.xdg.enable) then
        "k9s/skins/${name}.yaml"
      else
        "Library/Application Support/k9s/skins/${name}.yaml") {
          source = yamlFormat.generate "k9s-skin-${name}.yaml" value;
        }) cfg.skins;
```

Of course, an easy workaround is to enable XDG in your home-manager config and then export the XDG environment variables:
```nix
xdg = {
  enable = true;
};
```

**Comment by alejandro-angulo** [comment]
I ran into this exact issue earlier today. I opened up PR #311 .

@m-wynn Would you mind testing out the change if you get a chance please? My repo is https://github.com/alejandro-angulo/catppuccin-nix/.

**Comment by m-wynn** [comment]
Thanks @alejandro-angulo.  This worked for me as expected both with and without xdg.
