### ISSUE TITLE
Weird evaluation warning when rebuilding (NixOS)

### ISSUE THREAD

**Issue by Vartroc** [catppuccin/nix#353]
`trace: evaluation warning: The option `colorschemes.catppuccin.flavour' defined in `/nix/store/i6i3r1vqa5wz6d8apj9d27lmr6vgg306-source/modules/nixvim/nixvim.nix' has been renamed to `colorschemes.catppuccin.settings.flavour'.`

First of all, `colorschemes.catppuccin.flavour` does not work. It has to be `colorschemes.catppuccin.flavor`
And when trying to add a settings, I get the error:
```
error:
       … while calling the 'head' builtin

         at /nix/store/60sn02zhawl3kwn0r515zff3h6hg6ydz-source/lib/attrsets.nix:1575:11:

         1574|         || pred here (elemAt values 1) (head values) then
         1575|           head values
             |           ^
         1576|         else

       … while evaluating the attribute 'value'

         at /nix/store/60sn02zhawl3kwn0r515zff3h6hg6ydz-source/lib/modules.nix:816:9:

          815|     in warnDeprecation opt //
          816|       { value = addErrorContext "while evaluating the option `${showOption loc}':" value;
             |         ^
          817|         inherit (res.defsFinal') highestPrio;

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: The option `home-manager.users.andi.catppuccin.settings' does not exist. Definition values:
       - In `/nix/store/6v9mzbryyp9bxfi4yz9i7cb4i9cyfrj2-source/modules/home-manager/theming.nix':
           {
             flavor = "mocha";
           }
```

**Comment by isabelroses** [comment]
The first part seems to be a nixvim issue, but the later trace shows, a catppuccin/nix issue. catppuccin/nvim still uses the British spelling of `flavour` and therefore so does nixvim. So the original text seems unrelated to the trace, unless you made a typo for your nixvim config.

And from `home-manager.users.andi.catppuccin.settings.flavor = "mocha";` should be `home-manager.users.andi.catppuccin.flavor = "mocha";`
