### ISSUE TITLE
Error referencing 'catppuccin-grub-theme' on system without grub

### ISSUE THREAD

**Issue by ozmodeuz** [catppuccin/nix#362]
Trying to add catppuccin with the global enable flag I get the following error:

```
       error: The option `home-manager.users.oz.boot.loader.grub.font' does not exist. Definition values:
       - In `/nix/store/1qqg71jv43w66mhgjfkp3d91xizk1v4s-source/modules/nixos/grub.nix':
           {
             _type = "if";
             condition = false;
             content = "/nix/store/2jsy9midp0vzg9jcids65vx2xzcy712l-catppuccin-grub-theme/font.pf2";
```
What is odd is that my nixos config doesn't include grub (and contains no references to grub that I can find, and I get the same error if I explicitly disable grub in my config.

I'm using nixos-24.05, and have added catppuccin to my flake in my nixos config and home-manager config; and then using 'catppuccin.enable = true' in nixos config.

Any ideas?

**Comment by ozmodeuz** [comment]
Edited the title; the former was the (different) error I get when I enable catppuccin globally via Home Manager instead of nixos config.

**Comment by isabelroses** [comment]
From the looks of the trace, i would say it looks like your importing `inputs.catppuccin.nixosModules.catppuccin` somewhere inside of your home-manager config. But you only want to use `inputs.catppuccin.homeManagerModules.catppuccin`.

**Comment by ozmodeuz** [comment]
Oops, user error. Had 'catppuccin.nixosModules.catppuccin' in both nixos config and home-manager... ignore!!

**Comment by ozmodeuz** [comment]
Our messages crossed!
