### ISSUE TITLE
Add support for rofi-wayland

### ISSUE THREAD

**Issue by haylinmoore** [catppuccin/nix#364]
https://github.com/A417ya/rofi-wayland/

**Comment by isabelroses** [comment]
We currently have support for rofi, https://github.com/catppuccin/nix/blob/main/modules/home-manager/rofi.nix. So assuming you want to use rofi with wayland support you would do:

```nix
{pkgs, ...}: {
  programs.rofi = {
    enable = true;
    catppuccin.enable = true;
    package = pkgs.rofi-wayland;
   };
 }
 ```
