### ISSUE TITLE
fromINI sans IFD

### ISSUE THREAD

**Issue by mightyiam** [catppuccin/nix#373]
If we're not aiming for actual INI parsing (is there even a formal spec?), parsing [these](https://github.com/catppuccin/swaylock/blob/77246bbbbf8926bdb8962cffab6616bc2b9e8a06/themes/macchiato.conf) in Nix shouldn't take too long.

Would such a change be accepted?

https://github.com/search?q=repo%3Acatppuccin%2Fnix%20fromini&type=code

- https://github.com/catppuccin/nix/blob/32359bf226fe874d3b7a0a5753d291a4da9616fe/modules/home-manager/swaylock.nix#L37
  https://github.com/catppuccin/swaylock/blob/77246bbbbf8926bdb8962cffab6616bc2b9e8a06/themes/macchiato.conf
- https://github.com/catppuccin/nix/blob/32359bf226fe874d3b7a0a5753d291a4da9616fe/modules/home-manager/imv.nix#L11
  https://github.com/catppuccin/imv/blob/0317a097b6ec8122b1da6d02f61d0c5158019f6e/themes/macchiato.config
- https://github.com/catppuccin/nix/blob/32359bf226fe874d3b7a0a5753d291a4da9616fe/modules/home-manager/mako.nix#L11-L13
  https://github.com/catppuccin/mako/blob/92844f144e72f2dc8727879ec141ffdacf3ff6a1/themes/catppuccin-frappe/catppuccin-frappe-blue
- https://github.com/catppuccin/nix/blob/32359bf226fe874d3b7a0a5753d291a4da9616fe/modules/home-manager/cava.nix#L14
  https://github.com/catppuccin/cava/blob/0746f77974330338ee2e1e4d1ef9872eba57eb26/themes/frappe.cava

Can these possibly be parsed using `fromTOML`?

**Comment by mightyiam** [comment]
`fromTOML` seems to fail on the lack of quotes. Perhaps the hash is interpreted as a comment:

```
nix-repl> fromTOML (builtins.readFile ./catppuccin-frappe-blue)
error:
       … while calling the 'fromTOML' builtin
         at «string»:1:1:
            1| fromTOML (builtins.readFile ./catppuccin-frappe-blue)
             | ^

       error: while parsing TOML: [error] toml::parse_key_value_pair: missing value after key-value separator '='
        --> fromTOML
          |
        4 | text-color=#c6d0f5
          |            ^--- expected value, but got nothing
```

I thought perhaps the values could be quoted upstream, but that sounds risky, as I don't expect there's testing infra to make sure the programs parse the config files correctly.

**Comment by getchoo** [comment]
While removing IFD in fromINI itself is possible, it's not very useful in our case. Any approach here would require reading a file at some point, and as we rely entirely on remote sources, that is going to inevitably result in IFD (aside from the workaround with builtin fetchers I described in https://github.com/catppuccin/nix/pull/377). We would only be moving the problem
