### ISSUE TITLE
How to override some colors?

### ISSUE THREAD

**Issue by kesor** [catppuccin/nix#395]
I am trying to make fzf background black instead of the default mocha theme background. Using home manager standalone.

This throws an error about double declaration,

```
programs.fzf.colors.bg = "#000000";
```

Tried these, but none of them work -

```
prorgams.fzf.colors.bg = lib.mkForce "#000000";

programs.fzf.colors = lib.mkForce { bg = "#000000"; };
```

Looking at the code for catppuccin, there doesn't seem to be a way to override individual colors either.

What am I missing here?

**Comment by arminius-smh** [comment]
> ```nix
> programs.fzf.colors = lib.mkForce { bg = "#000000"; };
> ```

I think this overrides every color set by cappuccin and only sets the background color to black? So you probably don't want to use that

> ```nix
> prorgams.fzf.colors.bg = lib.mkForce "#000000";
> ```

This however should work / works for me, could you elaborate on what you mean with they "don't work"?

Keep in mind after you change the options you may need to log-out & log-in again, since fzf options are set by the `FZF_DEFAULT_OPTS` env variable

**Comment by kesor** [comment]
I have this in `home.nix`,

```
  programs.fzf = {
    enable = true;
    catppuccin.enable = true;
    defaultCommand = "fd --type f --strip-cwd-prefix --exclude .git";
    tmux.enableShellIntegration = true;
    enableBashIntegration = true;
    colors.bg = lib.mkForce "#010203";
  };
```

And after switching, it still does not show up.

```
› grep -i FZF /home/evgeny/.nix-profile/etc/profile.d/hm-session-vars.sh
export FZF_DEFAULT_COMMAND="fd --type f --strip-cwd-prefix --exclude .git"
export FZF_DEFAULT_OPTS="--color bg:#010203,bg+:#313244,fg:#cdd6f4,fg+:#cdd6f4,header:#89b4fa,hl:#89b4fa,hl+:#89b4fa,info:#89b4fa,marker:#89b4fa,pointer:#89b4fa,prompt:#89b4fa,spinner:#f5e0dc"
export FZF_TMUX="1"
```

**Comment by kesor** [comment]
Overriding just `colors.bg` seems to have worked. Made sure to check in `$HOME/.nix-profile/etc/profile.d/hm-session-vars.sh` and it appears correctly.
