### ISSUE TITLE
bat theme not work

### ISSUE THREAD

**Issue by birdmanmandbir** [catppuccin/nix#67]
bat give me this warning:
>[bat warning]: Unknown theme 'Catppuccin-mocha', using default.

**Comment by birdmanmandbir** [comment]
I have tried it, but it still doesn’t work.
<img width="726" alt="image" src="https://github.com/Stonks3141/ctp-nix/assets/48193000/464be75d-6ee9-4d2c-a016-dbddf4b53982">
<img width="1500" alt="image" src="https://github.com/Stonks3141/ctp-nix/assets/48193000/d2b95891-fee6-429f-8bcf-37ce55a8ab29">

my inputs:
```nix
home-manager.url = "github:nix-community/home-manager";
catppuccin.url = "github:Stonks3141/ctp-nix";
```

**Comment by getchoo** [comment]
what revision of home-manager is this? given the [current](https://github.com/nix-community/home-manager/blob/93e804e7f8a1eb88bde6117cd5046501e66aa4bd/modules/programs/bat.nix#L146) way themes are handled, it should not be possible for the name of the symlink to differ from that of the target with our configuration. specifically, `"${name}.tmTheme` and `val.file` will always be equal to each other in the `mapAttrsToList` function. i would recommend updating home-manager and regenerating this symlink

**Comment by birdmanmandbir** [comment]
Thank you! I removed `bat` and reinstalled it by modifying the `programs.bat.enable = true`, After doing so, the name of the symlink is now correct.
<img width="1507" alt="image" src="https://github.com/Stonks3141/ctp-nix/assets/48193000/d32a6e58-7d24-4dd9-a85a-5bcff88da041">
I believe that the symlink’s name is not updated after switching home-manager.

**Comment by getchoo** [comment]
closing this as most likely there's an issue with home-manager itself; you will probably get better support there. feel free to re-open if i misunderstood, though :)
