### ISSUE TITLE
expose palette to lib

### ISSUE THREAD

**Issue by pinkcreeper100** [catppuccin/nix#96]
to allow usage for applications/modules that don't yet have a port

**Comment by getchoo** [comment]
i'm not sure if i like this idea. my hope is that one day we won't need to use this palette internally and can depend fully on the individual ports, as they will be better maintained than any one recreated via the palette here; i would rather not be held back on this. we also don't expose any library currently, and i have never really intended to. the functions themselves don't serve much purpose outside of this project, so the only reason to expose a library would be this palette. is that worth it?

i do want to make the `sources` attribute more accessible and (hopefully) customizable, though. it could be a better way to go about it, as it wouldn't trap up is in trying to keep another public api stable, but would still allow for reuse of our internal sources by end users - which imo has more benefit than only exposing palette

**Comment by michaelBelsanti** [comment]
I agree, I think using [nix-colors](https://github.com/misterio77/nix-colors) is a better bet if you want access the catppuccin palette in your config. I use it alongside this repo.

**Comment by jh-devv** [comment]
I just think adding at least something for so the user could access the palette would be good since I don't want to use `nix-colors` just for that?

**Comment by getchoo** [comment]
> @getchoo Does #129 handle that?

yes, but there will be no promises of stability. if we're able to apply all themes without the palette, it will be removed
